spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sallejoven
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      minimumIdle: 5
      maximumPoolSize: 10
    platform: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 120MB

  logging:
    level:
      org.springframework: DEBUG

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

server:
  port: 8080