spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sallejoven
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      minimumIdle: 5
      maximumPoolSize: 10
    platform: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 120MB

  logging:
    level:
      org.springframework: DEBUG

  # SMTP Gmail para pruebas
  mail:
    host: smtp.gmail.com
    port: 587
    username: jfdeznoz@gmail.com     # tu cuenta Gmail local
    password: bhka rxso nzkp ucio    # App Password de Google
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"  

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem

salle:
  aws:
    access-key: AKIAZTJUYOCXBY7Q6Q6L
    secret-key: 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
    bucket-name: sallejoven-events
    bucket-url: https://sallejoven-events.s3.eu-north-1.amazonaws.com/
  image-extensions-allowed: jpg,png,jpeg,webp

app:
  email:
    notifications: true

server:
  port: 8080