CREATE TABLE IF NOT EXISTS public.user_center (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_salle   BIGINT       NOT NULL,
  center       BIGINT       NOT NULL,
  user_type    SMALLINT     NOT NULL,
  year         INTEGER      NOT NULL,
  deleted_at   TIMESTAMP    NULL
);

ALTER TABLE public.user_center
  ADD CONSTRAINT fk_user_center_user
  FOREIGN KEY (user_salle) REFERENCES public.user_salle (id);

ALTER TABLE public.user_center
  ADD CONSTRAINT fk_user_center_center
  FOREIGN KEY (center) REFERENCES public.center (id);

ALTER TABLE public.user_center
  ADD CONSTRAINT chk_user_center_user_type
  CHECK (user_type IN (2,3));

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_center_active
  ON public.user_center (user_salle, center, year, user_type)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_user_center_user_year
  ON public.user_center (user_salle, year)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_user_center_center_year
  ON public.user_center (center, year)
  WHERE deleted_at IS NULL;
