CREATE TABLE user_pending (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  last_name        VARCHAR(255)            NOT NULL,
  dni              VARCHAR(64)             NOT NULL,
  phone            VARCHAR(64),
  email            VARCHAR(255)            NOT NULL,
  tshirt_size      INTEGER,
  health_card_number VARCHAR(128),
  intolerances     VARCHAR(1024),
  chronic_diseases VARCHAR(1024),
  city             VARCHAR(255),
  address          VARCHAR(255),
  image_authorization BOOLEAN,
  birth_date       DATE,
  roles            VARCHAR(255),
  password         VARCHAR(255)            NOT NULL,
  gender           INTEGER,
  mother_full_name VARCHAR(255),
  father_full_name VARCHAR(255),
  mother_email     VARCHAR(255),
  father_email     VARCHAR(255),
  father_phone     VARCHAR(64),
  mother_phone     VARCHAR(64),

  center_id        BIGINT,
  group_id         BIGINT,

  created_at       TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_pending_email ON user_pending(email);
CREATE INDEX idx_user_pending_dni   ON user_pending(dni);
CREATE INDEX idx_user_pending_center ON user_pending(center_id);
CREATE INDEX idx_user_pending_group  ON user_pending(group_id);