name: Deploy Spring Boot to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      S3_BUCKET: salle-joven-bucket
      EB_APP_NAME: salle-joven-prod-env
      EB_ENV_NAME: salle-joven-prod-env-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Package application
        run: |
          mkdir deploy
          cp target/*.jar deploy/app.jar
          cd deploy
          zip app.zip app.jar

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp deploy/app.zip s3://$S3_BUCKET/app.zip --region $AWS_REGION

          aws elasticbeanstalk create-application-version \
            --application-name $EB_APP_NAME \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=$S3_BUCKET,S3Key=app.zip \
            --region $AWS_REGION

          aws elasticbeanstalk update-environment \
            --application-name $EB_APP_NAME \
            --environment-name $EB_ENV_NAME \
            --version-label ${{ github.sha }} \
            --region $AWS_REGION