name: Deploy Spring Boot to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      S3_BUCKET: salle-joven-bucket
      EB_APP_NAME: starcheck-salle-joven-pro
      EB_ENV_NAME: Starcheck-salle-joven-pro-env
      ZIP_KEY: app-${{ github.sha }}.zip
      VERSION_LABEL: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Package application (rename to application.jar)
        run: |
          mkdir -p deploy
          JAR=$(ls target/*.jar | grep -v '\.original$' | head -n 1)
          cp "$JAR" deploy/application.jar
          cd deploy
          zip "$ZIP_KEY" application.jar
          ls -l

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload bundle to S3
        run: aws s3 cp "deploy/$ZIP_KEY" "s3://$S3_BUCKET/$ZIP_KEY"

      - name: Create EB application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "$EB_APP_NAME" \
            --version-label "$VERSION_LABEL" \
            --source-bundle S3Bucket="$S3_BUCKET",S3Key="$ZIP_KEY"

      - name: Deploy to EB environment
        run: |
          aws elasticbeanstalk update-environment \
            --application-name "$EB_APP_NAME" \
            --environment-name "$EB_ENV_NAME" \
            --version-label "$VERSION_LABEL"
            --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=SPRING_PROFILES_ACTIVE,Value=prod